name: Release – Build and Publish
run-name: Build and Publish – ${{ github.ref_name }}

on:
  push:
    branches: ["**"]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches: [main]

permissions:
  contents: write
  id-token: write

jobs:
  pipeline:
    uses: ./.github/workflows/publish.yml
    with:
      working-directory: bridge-react
      setup-bun: true
      setup-pnpm: false
      install-command: bun install
      build-command: bun run build
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      docs-sync-key: ${{ secrets.DOCS_SYNC_KEY }}



